// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm2dkQsiY1_F9vB-wwEozQrV9aLd3026A',
    appId: '1:165715140888:web:8c3aa75fc4f2d0fd303e6d',
    messagingSenderId: '165715140888',
    projectId: 'chatify-78de3',
    authDomain: 'chatify-78de3.firebaseapp.com',
    storageBucket: 'chatify-78de3.appspot.com',
    measurementId: 'G-VFGK506WZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq2XqraT0i_6g4e6m02IfAgjxAa-akQNI',
    appId: '1:165715140888:android:68c99f03efad6a13303e6d',
    messagingSenderId: '165715140888',
    projectId: 'chatify-78de3',
    storageBucket: 'chatify-78de3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhdQPLgy8w1fUcnLDbMHw8hMjSP8EUydw',
    appId: '1:165715140888:ios:977e4010f6155af0303e6d',
    messagingSenderId: '165715140888',
    projectId: 'chatify-78de3',
    storageBucket: 'chatify-78de3.appspot.com',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhdQPLgy8w1fUcnLDbMHw8hMjSP8EUydw',
    appId: '1:165715140888:ios:2ffb940ebd67e397303e6d',
    messagingSenderId: '165715140888',
    projectId: 'chatify-78de3',
    storageBucket: 'chatify-78de3.appspot.com',
    iosBundleId: 'com.example.chatify.RunnerTests',
  );
}
